export const RESTART_GAME = 'RESTART_GAME';
export const RESTART_GAME_BEFORE = 'RESTART_GAME_BEFORE';
export const TOGGLE_GAME = 'TOGGLE_GAME';
export const RESET_GAME = 'RESET_GAME';
export const RESET_GAME_BEFORE = 'RESET_GAME_BEFORE';
export const OVER_GAME = 'OVER_GAME';
export const REVIVE_GAME = 'REVIVE_GAME';

export const CHANGE_GRID_ROW_NUM = 'CHANGE_GRID_ROW_NUM';
export const CHANGE_GRID_COL_NUM = 'CHANGE_GRID_COL_NUM';
export const CHANGE_SNAKE_SPEED = 'CHANGE_SNAKE_SPEED';
export const CHANGE_SNAKE_CAN_HIT_SELF = 'CHANGE_SNAKE_CAN_HIT_SELF';

export const SNAKE_GO = 'SNAKE_GO';
export const SNAKE_GO_WITH_DATA = 'SNAKE_GO_WITH_DATA';
export const EAT_FOOD = 'EAT_FOOD';
export const CREATE_FOOD = 'CREATE_FOOD';
export const CREATE_FOOD_WITH_DATA = 'CREATE_FOOD_WITH_DATA';
export const CHANGE_DIRECTION = 'CHANGE_DIRECTION';

export const SAVE_STATE = 'SAVE_STATE';
export const LOAD_STATE = 'LOAD_STATE';
export const LOAD_STATE_WITH_DATA = 'LOAD_STATE_WITH_DATA';