export const RESTART_GAME = 'RESTART_GAME';
export const TOGGLE_GAME = 'TOGGLE_GAME';
export const RESET_GAME = 'RESET_GAME';
export const RESTART_GAME_WITH_FOOD = 'RESTART_GAME_WITH_FOOD';
export const RESET_GAME_WITH_FOOD = 'RESET_GAME_WITH_FOOD';

export const CHANGE_GRID_ROW_NUM = 'CHANGE_GRID_ROW_NUM';
export const CHANGE_GRID_COL_NUM = 'CHANGE_GRID_COL_NUM';
export const CHANGE_SNAKE_SPEED = 'CHANGE_SNAKE_SPEED';

export const SNAKE_GO = 'SNAKE_GO';
export const CHANGE_DIRECTION = 'CHANGE_DIRECTION';